import { Button } from '@/components/ui/button';

export function HomePage({english = false}: {english?: boolean}) {
  const t = (zh: string, en: string) => english ? en : zh;
  return <div lang={english ? 'en' : 'zh-Hans'}>
    <a className="skip" href="#main">{t('跳到正文','Skip to content')}</a>
    <header className="header wrap"><a className="brand" href="/" aria-label="LightVibe"><img src="/icon.png" width="40" height="40" alt="" />LightVibe</a><nav aria-label={t('主导航','Main navigation')}><a href="#setup">{t('连接指南','Setup')}</a><a href="#download">{t('下载','Download')}</a><a href={english ? '/' : '/en/'} hrefLang={english ? 'zh-Hans' : 'en'}>{english ? '中文' : 'English'}</a></nav></header>
    <main id="main" className="wrap">
      <section className="hero"><div><p className="eyebrow">VOICE IN. IDEAS OUT.</p><h1>{t('轻声说出想法。','Speak your idea.')}<br/><span>{t('让灵感继续。','Keep your flow.')}</span></h1><p className="lead">{t('用 iPhone 或 Apple Watch 把指令交给 Mac 上的 Codex。少一点来回切换，多一点专注。','Send instructions to Codex on your Mac from your iPhone or Apple Watch. Less switching. More focus.')}</p><a className="primary" href="#download">{t('获取 LightVibe Bridge','Get LightVibe Bridge')} <span aria-hidden="true">↗</span></a><p className="caption">{t('开发中 · 尚未在 App Store 上架','In development · Not yet available on the App Store')}</p></div><div className="hero-art"><img src="/icon.png" width="1024" height="1024" alt="LightVibe"/><p>iPhone <span>＋</span> Apple Watch <span>＋</span> Mac</p></div></section>
      <section className="features" aria-label={t('首发方向','Planned first release')}><article><span className="index">01 / VOICE</span><h2>{t('想法，不必等键盘','Ideas beyond the keyboard')}</h2><p>{t('轻声输入，发送到选中的 Mac 任务。首版面向同一可信网络内的设备。','Speak and send to your selected Mac task. The first release is designed for devices on the same trusted network.')}</p></article><article><span className="index">02 / STATUS</span><h2>{t('最近 5 个任务，一眼掌握','Five recent tasks at a glance')}</h2><p>{t('关注任务状态和最新回复。失去实时连接时显示待刷新，不把旧状态当作当前进度。','Follow task status and the latest reply. Unavailable live status is marked stale rather than presented as current.')}</p></article><article><span className="index">03 / FOCUS</span><h2>{t('工作时安静，完成时提醒','Quiet while working')}</h2><p>{t('后台提醒、Watch 与灵动岛是首发方向。通知受网络、授权、专注模式及系统调度影响。','Background alerts, Watch and Live Activity support are planned for launch. Delivery depends on network, permissions and system settings.')}</p></article></section>
      <section id="setup" className="section"><div className="section-head"><p className="eyebrow">GET CONNECTED</p><h2>{t('三台设备，同一个思路。','Three devices. One flow.')}</h2></div><ol className="steps"><li><span>01</span><div><h3>{t('在 Mac 准备 Bridge','Prepare your Mac')}</h3><p>{t('正式安装包发布后，安装 LightVibe Bridge，并按引导检查已安装的 Codex。Mac 需要保持运行和联网。','When the release is available, install LightVibe Bridge and follow its Codex compatibility check. Keep your Mac running and connected.')}</p></div></li><li><span>02</span><div><h3>{t('同网连接，扫码配对','Connect and pair')}</h3><p>{t('iPhone 与 Mac 连接同一可信网络，在 LightVibe 中扫描 Bridge 配置二维码。不要公开分享配对二维码。','Connect iPhone and Mac to the same trusted network, then scan the Bridge pairing code in LightVibe. Keep pairing codes private.')}</p></div></li><li><span>03</span><div><h3>{t('选择任务，开始说话','Choose a task. Speak.')}</h3><p>{t('确认发送目标，授予所需麦克风、语音识别及通知权限。按界面提示测试手机和手表的提醒。','Confirm your target task and grant the required microphone, speech recognition and notification permissions. Test alerts on each device.')}</p></div></li></ol><p className="note">{t('首版不提供审批提醒或移动端批准／拒绝操作；离开局域网不能据此远程发送指令。','The first release does not include approval alerts or mobile approval actions. Local pairing does not enable remote commands outside your network.')}</p></section>
      <section id="download" className="download"><div><p className="eyebrow">LIGHTVIBE BRIDGE FOR MAC</p><h2>{t('下载准备中','Download coming soon')}</h2><p>{t('我们正在完善独立安装、签名与公证。正式包就绪前，不公开开发测试安装包。','We are preparing standalone installation, signing and notarization. Development-only installers are not publicly distributed.')}</p><p className="caption">{t('基础功能计划免费 · 正式系统要求将在发布时公布','Core features planned to be free · Final system requirements will be published with the release')}</p></div><div className="download-action"><Button disabled className="download-button">{t('Mac 安装包准备中','Mac installer coming soon')}</Button><a href="mailto:kefu.jingjianbao@qq.com">{t('联系技术支持','Contact support')} <span aria-hidden="true">↗</span></a></div></section>
      <section id="privacy" className="section privacy"><p className="eyebrow">PRIVACY & SUPPORT</p><h2>{t('你的想法，值得被认真保护。','Your ideas deserve care.')}</h2><p>{t('这个网站只提供项目说明，不收集录音、不提供在线任务控制，也没有广告、分析脚本或账号注册。网站托管方可能处理 IP 地址及访问日志；向支持邮箱发信会由邮件服务商处理。','This website provides project information only. It has no recording, online task control, advertising, analytics scripts or account registration. The hosting provider may process IP addresses and access logs; support emails are handled by email providers.')}</p><p>{t('App 公开版尚未发布，完整 App 隐私政策将在数据处理方案确定后公布。不要向支持邮箱发送密码、API 密钥、配对码或完整私密对话。','The public app is not yet released. Its full privacy policy will be published once data handling is finalized. Do not email passwords, API keys, pairing codes or private conversations.')}</p><a href="mailto:kefu.jingjianbao@qq.com">kefu.jingjianbao@qq.com</a></section>
    </main><footer className="wrap"><span>© 2026 LightVibe</span><a href="#privacy">{t('网站隐私与支持','Website privacy & support')}</a><p>{t('独立项目，非 OpenAI 或 Apple 官方产品。','An independent project, not an official OpenAI or Apple product.')}</p></footer>
  </div>;
}
